### ISSUE TITLE
Criação da Matriz de Competências

### ISSUE THREAD

**Issue by moonshinerd** [unb-mds/2024-1-Squad-03#1]
Esta issue tem como objetivo coordenar a criação da Matriz de Competências da equipe, conforme discutido na reunião realizada em 27/03/2024. A Matriz de Competências é uma ferramenta essencial para identificar as habilidades e conhecimentos disponíveis em tecnologias dentro da equipe, permitindo uma alocação mais eficiente de recursos e o desenvolvimento de estratégias de capacitação. O objetivo é desenvolver um formulário que permita a cada membro da equipe informar suas capacidades e habilidades em tecnologias específicas. O formulário deve ser projetado de maneira clara e abrangente, abordando as principais áreas de conhecimento relevantes para o projeto em questão.

**Comment by Otavio4283** [comment]
Feita a 
[https://docs.google.com/document/d/1cd-01Lyy_pfJfEnJ2HAsMCuFQ9tUBLgD07XcGqS9q58/edit](url)
