### ISSUE TITLE
Implementação do Github Projects

### ISSUE THREAD

**Issue by Marcelo-Adrian** [unb-mds/2024-1-Squad-03#23]
## Descrição

Esta issue destina-se a implementar o GitHub Projects em nosso repositório para gerenciar e acompanhar o progresso das tarefas relacionadas ao projeto.

## Tarefas

- [x] **Permissão para o GitHub Projects:** Conseguir a permissão para que possa ser criado o Projects no repositório.
- [x] **Configurar o quadro Kanban:** Configurar o GitHub Projects no repositório para criar um quadro de kanban que represente o fluxo de trabalho do projeto.
- [x] **Criar Listas:** Criar listas no quadro do GitHub Projects para representar diferentes etapas do processo, como "A Fazer", "Em Progresso", "Revisão", e "Concluído".

## Critérios de Avaliação

- [x] Configuração bem-sucedida do GitHub Projects no repositório.
- [x] Criação de listas que representem de forma adequada o fluxo de trabalho do projeto.
- [x] Integração adequada entre as tarefas do GitHub Projects e as issues do repositório.
- [x] Repasse com os outros integrantes a cerca de sua funcionalidade e usabilidade.

## Encerramento

Esta issue será considerada concluída quando todas as tarefas descritas acima estiverem implementadas e o GitHub Projects estiver configurado e em pleno funcionamento no repositório.

**Comment by thaleseuflauzino** [comment]
A issue de implementação do GitHub Projects foi concluída com sucesso. Após obtermos a permissão necessária, configuramos o GitHub Projects em nosso repositório, criando um quadro Kanban que reflete fielmente o fluxo de trabalho do projeto. Foram criadas listas representando as etapas do processo, como "Em desenvolvimento", "Em Progresso", "Em Revisão", "Pronto" e "Finalizado", garantindo uma organização eficaz das tarefas.

Além disso, realizamos uma integração adequada entre as tarefas do GitHub Projects e as issues do repositório, facilitando o acompanhamento do progresso do projeto e garantindo uma comunicação clara entre os membros da equipe.

Estou à disposição para quaisquer dúvidas ou ajustes adicionais que possam ser necessários.
