### ISSUE TITLE
Documentar o Story Map

### ISSUE THREAD

**Issue by m4rllon** [unb-mds/2024-1-Squad-03#25]
### Objetivo

Essa issue tem como objetivo documentar todo o Story Map que foi elaborado e definido na sprint anterior. Para isso, o documento deve descrever todas as jornadas do usuário que estarão presentes no sistema, suas tasks e as características da persona. Para que essa issue seja dada como concluida, o documento deve conter todas as informações descreitas de forma clara e objetiva.

### Tarefas

- [x] Documentar as histórias do usuário
- [x] Documentar pontos de sprint
- [x] Documentar cronograma dos MVPs

### Critérios de Aceitação

- [x] O documento deve conter todas as informações descreitas de forma clara e objetiva

**Comment by MariaCHelena** [comment]
Documento de user stories criado no link: [https://docs.google.com/document/d/1G9ORcn295m-Q98GP_yhVr7xXkms3z931ahfN3zf7W3c/edit?usp=sharing](docs).
