### ISSUE TITLE
Treinamento de Python

### ISSUE THREAD

**Issue by moonshinerd** [unb-mds/2024-1-Squad-03#3]
Esta issue tem como objetivo organizar um treinamento completo em Python para que os membros da equipe possam utilizar a linguagem Python de forma abrangente como uma das ferramentas essenciais dentro do projeto.

**Comment by thaleseuflauzino** [comment]
Foi realizado uma pesquisa de forma abrangente sobre a linguagem e também uma pesquisa mais específica na biblioteca Querido-Diario-ToolBox, links disponíveis [aqui](https://github.com/unb-mds/2024-1-Squad-03/blob/main/Estudos/Estudos.txt)
