### ISSUE TITLE
Treinamento Querido Diário

### ISSUE THREAD

**Issue by moonshinerd** [unb-mds/2024-1-Squad-03#4]
Esta issue destina-se a acompanhar e documentar o processo de treinamento para implementar o recurso "Querido Diário". O objetivo principal deste treinamento é capacitar a equipe para desenvolver e integrar uma funcionalidade que permitirá aos usuários registrarem seus pensamentos, sentimentos e eventos significativos em um formato de diário dentro da nossa aplicação. Durante este processo de treinamento, os membros da equipe serão orientados sobre os requisitos funcionais e não funcionais do recurso, as tecnologias relevantes a serem utilizadas, os padrões de codificação a serem seguidos e os testes necessários para garantir a qualidade do produto final. Além disso, serão atribuídas tarefas específicas e haverá revisões regulares do progresso para garantir que todos estejam alinhados e progredindo efetivamente em direção à conclusão bem-sucedida deste projeto.

**Comment by MariaCHelena** [comment]
Essa issue vai ficar aberta pra ser finalizada na próxima sprint.
