### ISSUE TITLE
Desenvolver Feed de Licitações

### ISSUE THREAD

**Issue by MariaCHelena** [unb-mds/2024-1-Squad-03#66]
**Descrição/Objetivo:**
Com as licitações já coletadas e devidamente documentadas no Backend, o próximo passo será implementar essas licitações no FrontEnd da nossa aplicação, para que os usuários possam ter acesso e visualizar o feed das licitações.

**Tarefas:**
- [ ] Finalizar a estilização dos cards de licitação.
- [ ] Obter os dados de licitação do Backend.
- [ ] Desenvolver o feed de licitação com paginação.

**Comment by m4rllon** [comment]
O feed de licitações foi desenvolvido pelos dois membros conforme combinado.
